apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1  # <-- Suba pelo menos 1 para testar
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        env:
        # Configuração do banco de dados PostgreSQL
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: postgres.n8n.svc.cluster.local
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - name: DB_POSTGRESDB_USER
          value: n8n
        - name: DB_POSTGRESDB_PASSWORD
          value: n8neconomia

        # 🔒 Limita o pool de conexões para evitar "too many connections"
        - name: DB_POSTGRESDB_MAX_POOL_SIZE
          value: "5"
        - name: DB_POSTGRESDB_IDLE_TIMEOUT
          value: "30000"

        # Corrigir erro "X-Forwarded-For"
        - name: N8N_BASIC_AUTH_PROXY
          value: "true"

        # Configuração da porta
        - name: N8N_PORT
          value: "5678"

        # Configuração de rede para proxy reverso
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_HOST
          value: "n8n-planejamento.economia.go.gov.br"
        - name: N8N_EDITOR_BASE_URL
          value: "https://n8n-planejamento.economia.go.gov.br"
        - name: N8N_WEBHOOK_URL
          value: "https://n8n-planejamento.economia.go.gov.br/"

        # Autenticação no painel
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          value: admin
        - name: N8N_BASIC_AUTH_PASSWORD
          value: adminpassword

        # Corrigir permissões do arquivo /home/node/.n8n/config
        - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
          value: "true"

        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-pvc-new

