apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc-new
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany  #Corrigido para RWX
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
